// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
// 	protoc-gen-mcp {{ .Version }}
// source: {{ .SourcePath }}
// Include this from your C++ main to call MCP lifecycle functions.

#pragma once

#include "rust/cxx.h"
#include "{{ .CrateName }}/lib.rs.h"
