# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp/protobuf/prompt.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'mcp/protobuf/prompt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mcp.protobuf import ui_pb2 as mcp_dot_protobuf_dot_ui__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19mcp/protobuf/prompt.proto\x12\x0cmcp.protobuf\x1a\x15mcp/protobuf/ui.proto\"Y\n\tMCPPrompt\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription\x12\x16\n\x06schema\x18\x03 \x01(\tR\x06schema\"\xa0\x01\n\x0eMCPToolOptions\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription\x12\x1f\n\x08progress\x18\x03 \x01(\x08H\x00R\x08progress\x88\x01\x01\x12*\n\x02ui\x18\x04 \x01(\x0b\x32\x1a.mcp.protobuf.MCPUIOptionsR\x02uiB\x0b\n\t_progressBa\n\x10\x63om.mcp.protobufB\x0bPromptProtoP\x01Z>github.com/machanirobotics/grpc-mcp-gateway/mcp/protobuf/mcppbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp.protobuf.prompt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.mcp.protobufB\013PromptProtoP\001Z>github.com/machanirobotics/grpc-mcp-gateway/mcp/protobuf/mcppb'
  _globals['_MCPPROMPT']._serialized_start=66
  _globals['_MCPPROMPT']._serialized_end=155
  _globals['_MCPTOOLOPTIONS']._serialized_start=158
  _globals['_MCPTOOLOPTIONS']._serialized_end=318
# @@protoc_insertion_point(module_scope)
