# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp/protobuf/ui.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'mcp/protobuf/ui.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15mcp/protobuf/ui.proto\x12\x0cmcp.protobuf\"1\n\x0cMCPUIOptions\x12!\n\x0cresource_uri\x18\x01 \x01(\tR\x0bresourceUri\"\xb5\x01\n\x10MCPUIResourceCsp\x12\'\n\x0f\x63onnect_domains\x18\x01 \x03(\tR\x0e\x63onnectDomains\x12)\n\x10resource_domains\x18\x02 \x03(\tR\x0fresourceDomains\x12#\n\rframe_domains\x18\x03 \x03(\tR\x0c\x66rameDomains\x12(\n\x10\x62\x61se_uri_domains\x18\x04 \x03(\tR\x0e\x62\x61seUriDomains\"\x95\x01\n\x10MCPUIPermissions\x12\x16\n\x06\x63\x61mera\x18\x01 \x01(\x08R\x06\x63\x61mera\x12\x1e\n\nmicrophone\x18\x02 \x01(\x08R\nmicrophone\x12 \n\x0bgeolocation\x18\x03 \x01(\x08R\x0bgeolocation\x12\'\n\x0f\x63lipboard_write\x18\x04 \x01(\x08R\x0e\x63lipboardWrite\"\xc6\x01\n\x11MCPUIResourceMeta\x12\x30\n\x03\x63sp\x18\x01 \x01(\x0b\x32\x1e.mcp.protobuf.MCPUIResourceCspR\x03\x63sp\x12@\n\x0bpermissions\x18\x02 \x01(\x0b\x32\x1e.mcp.protobuf.MCPUIPermissionsR\x0bpermissions\x12\x16\n\x06\x64omain\x18\x03 \x01(\tR\x06\x64omain\x12%\n\x0eprefers_border\x18\x04 \x01(\x08R\rprefersBorderB]\n\x10\x63om.mcp.protobufB\x07UIProtoP\x01Z>github.com/machanirobotics/grpc-mcp-gateway/mcp/protobuf/mcppbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp.protobuf.ui_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.mcp.protobufB\007UIProtoP\001Z>github.com/machanirobotics/grpc-mcp-gateway/mcp/protobuf/mcppb'
  _globals['_MCPUIOPTIONS']._serialized_start=39
  _globals['_MCPUIOPTIONS']._serialized_end=88
  _globals['_MCPUIRESOURCECSP']._serialized_start=91
  _globals['_MCPUIRESOURCECSP']._serialized_end=272
  _globals['_MCPUIPERMISSIONS']._serialized_start=275
  _globals['_MCPUIPERMISSIONS']._serialized_end=424
  _globals['_MCPUIRESOURCEMETA']._serialized_start=427
  _globals['_MCPUIRESOURCEMETA']._serialized_end=625
# @@protoc_insertion_point(module_scope)
