// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "mcp/protobuf/enum.proto" (package "mcp.protobuf", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * MCPEnumOptions attaches a description to an enum type.
 * Used as: option (mcp.protobuf.enum) = { description: "..." };
 * The description appears in the MCP tool inputSchema for enum fields.
 *
 * @generated from protobuf message mcp.protobuf.MCPEnumOptions
 */
export interface MCPEnumOptions {
    /**
     * Human-readable description of the enum (e.g. for JSON Schema).
     *
     * @generated from protobuf field: string description = 1
     */
    description: string;
}
/**
 * MCPEnumValueOptions attaches a description to an enum value.
 * Used as: ENUM_VALUE = 0 [(mcp.protobuf.enum_value) = { description: "..." }];
 * Value descriptions are combined into the schema description for the enum field.
 *
 * @generated from protobuf message mcp.protobuf.MCPEnumValueOptions
 */
export interface MCPEnumValueOptions {
    /**
     * Human-readable description of this enum value.
     *
     * @generated from protobuf field: string description = 1
     */
    description: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class MCPEnumOptions$Type extends MessageType<MCPEnumOptions> {
    constructor() {
        super("mcp.protobuf.MCPEnumOptions", [
            { no: 1, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MCPEnumOptions>): MCPEnumOptions {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<MCPEnumOptions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MCPEnumOptions): MCPEnumOptions {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string description */ 1:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MCPEnumOptions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string description = 1; */
        if (message.description !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mcp.protobuf.MCPEnumOptions
 */
export const MCPEnumOptions = new MCPEnumOptions$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MCPEnumValueOptions$Type extends MessageType<MCPEnumValueOptions> {
    constructor() {
        super("mcp.protobuf.MCPEnumValueOptions", [
            { no: 1, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MCPEnumValueOptions>): MCPEnumValueOptions {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<MCPEnumValueOptions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MCPEnumValueOptions): MCPEnumValueOptions {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string description */ 1:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MCPEnumValueOptions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string description = 1; */
        if (message.description !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mcp.protobuf.MCPEnumValueOptions
 */
export const MCPEnumValueOptions = new MCPEnumValueOptions$Type();
