// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "mcp/protobuf/field_type.proto" (package "mcp.protobuf", syntax proto3)
// tslint:disable
/**
 * MCPFieldType enumerates JSON Schema primitive types used by elicitation fields.
 *
 * @generated from protobuf enum mcp.protobuf.MCPFieldType
 */
export enum MCPFieldType {
    /**
     * Default value; treated as string.
     *
     * @generated from protobuf enum value: MCP_FIELD_TYPE_UNSPECIFIED = 0;
     */
    MCP_FIELD_TYPE_UNSPECIFIED = 0,
    /**
     * JSON Schema "string" type.
     *
     * @generated from protobuf enum value: MCP_FIELD_TYPE_STRING = 1;
     */
    MCP_FIELD_TYPE_STRING = 1,
    /**
     * JSON Schema "number" type (floating-point).
     *
     * @generated from protobuf enum value: MCP_FIELD_TYPE_NUMBER = 2;
     */
    MCP_FIELD_TYPE_NUMBER = 2,
    /**
     * JSON Schema "boolean" type.
     *
     * @generated from protobuf enum value: MCP_FIELD_TYPE_BOOLEAN = 3;
     */
    MCP_FIELD_TYPE_BOOLEAN = 3,
    /**
     * JSON Schema "integer" type.
     *
     * @generated from protobuf enum value: MCP_FIELD_TYPE_INTEGER = 4;
     */
    MCP_FIELD_TYPE_INTEGER = 4
}
