// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "mcp/protobuf/mime_type.proto" (package "mcp.protobuf", syntax proto3)
// tslint:disable
/**
 * MCPMimeType enumerates common MIME types for MCP resources.
 *
 * @generated from protobuf enum mcp.protobuf.MCPMimeType
 */
export enum MCPMimeType {
    /**
     * Default; treated as application/json.
     *
     * @generated from protobuf enum value: MCP_MIME_TYPE_UNSPECIFIED = 0;
     */
    MCP_MIME_TYPE_UNSPECIFIED = 0,
    /**
     * application/json
     *
     * @generated from protobuf enum value: MCP_MIME_TYPE_APPLICATION_JSON = 1;
     */
    MCP_MIME_TYPE_APPLICATION_JSON = 1,
    /**
     * text/plain
     *
     * @generated from protobuf enum value: MCP_MIME_TYPE_TEXT_PLAIN = 2;
     */
    MCP_MIME_TYPE_TEXT_PLAIN = 2,
    /**
     * text/html
     *
     * @generated from protobuf enum value: MCP_MIME_TYPE_TEXT_HTML = 3;
     */
    MCP_MIME_TYPE_TEXT_HTML = 3,
    /**
     * text/markdown
     *
     * @generated from protobuf enum value: MCP_MIME_TYPE_TEXT_MARKDOWN = 4;
     */
    MCP_MIME_TYPE_TEXT_MARKDOWN = 4,
    /**
     * application/xml
     *
     * @generated from protobuf enum value: MCP_MIME_TYPE_APPLICATION_XML = 5;
     */
    MCP_MIME_TYPE_APPLICATION_XML = 5,
    /**
     * application/octet-stream
     *
     * @generated from protobuf enum value: MCP_MIME_TYPE_APPLICATION_OCTET_STREAM = 6;
     */
    MCP_MIME_TYPE_APPLICATION_OCTET_STREAM = 6,
    /**
     * application/pdf
     *
     * @generated from protobuf enum value: MCP_MIME_TYPE_APPLICATION_PDF = 7;
     */
    MCP_MIME_TYPE_APPLICATION_PDF = 7,
    /**
     * image/png
     *
     * @generated from protobuf enum value: MCP_MIME_TYPE_IMAGE_PNG = 8;
     */
    MCP_MIME_TYPE_IMAGE_PNG = 8,
    /**
     * image/jpeg
     *
     * @generated from protobuf enum value: MCP_MIME_TYPE_IMAGE_JPEG = 9;
     */
    MCP_MIME_TYPE_IMAGE_JPEG = 9
}
