// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "mcp/protobuf/progress.proto" (package "mcp.protobuf", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * MCPProgress is sent in server-streaming RPC chunks to report progress to MCP clients.
 * Use in a oneof with your result type:
 *
 * 	message CreateTodoStreamChunk {
 * 	  oneof payload {
 * 	    mcp.protobuf.MCPProgress progress = 1;
 * 	    Todo result = 2;
 * 	  }
 * 	}
 * 	rpc CreateTodo(CreateTodoRequest) returns (stream CreateTodoStreamChunk) {
 * 	  option (mcp.protobuf.tool) = { progress: true };
 * 	}
 *
 * How to send _meta (MCP client):
 *
 * When calling a tool, include progressToken in params._meta. The progressToken
 * can be a string or integer; it correlates progress notifications with the request.
 *
 * 	{
 * 	  "method": "tools/call",
 * 	  "params": {
 * 	    "name": "counter_service-count_v1",
 * 	    "arguments": { "to": 5 },
 * 	    "_meta": { "progressToken": "abc123" }
 * 	  }
 * 	}
 *
 * The gateway forwards progressToken via gRPC metadata (key: mcp-progress-token).
 * gRPC servers can check metadata to only send MCPProgress chunks when requested.
 *
 * The plugin auto-generates MCP tool handlers that send progress notifications
 * and return the final result.
 *
 * @generated from protobuf message mcp.protobuf.MCPProgress
 */
export interface MCPProgress {
    /**
     * Progress value so far (must increase with each chunk).
     *
     * @generated from protobuf field: double progress = 1
     */
    progress: number;
    /**
     * Optional total; omit if unknown.
     *
     * @generated from protobuf field: optional double total = 2
     */
    total?: number;
    /**
     * Human-readable status message.
     *
     * @generated from protobuf field: string message = 3
     */
    message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class MCPProgress$Type extends MessageType<MCPProgress> {
    constructor() {
        super("mcp.protobuf.MCPProgress", [
            { no: 1, name: "progress", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "total", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MCPProgress>): MCPProgress {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.progress = 0;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<MCPProgress>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MCPProgress): MCPProgress {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double progress */ 1:
                    message.progress = reader.double();
                    break;
                case /* optional double total */ 2:
                    message.total = reader.double();
                    break;
                case /* string message */ 3:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MCPProgress, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double progress = 1; */
        if (message.progress !== 0)
            writer.tag(1, WireType.Bit64).double(message.progress);
        /* optional double total = 2; */
        if (message.total !== undefined)
            writer.tag(2, WireType.Bit64).double(message.total);
        /* string message = 3; */
        if (message.message !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mcp.protobuf.MCPProgress
 */
export const MCPProgress = new MCPProgress$Type();
