// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "mcp/protobuf/prompt.proto" (package "mcp.protobuf", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * MCPPrompt defines a reusable prompt template exposed at the service level.
 *
 * The arguments are defined as a proper proto message referenced by schema.
 * Field types, descriptions, required-ness, and enum values are all
 * derived from the referenced message's proto definition.
 *
 * Example:
 *   prompts: [
 *     {
 *       name: "summarize_todos"
 *       description: "Summarize all pending todo items for a user"
 *       schema: "todo.v1.SummarizeTodosArgs"
 *     }
 *   ]
 *
 * @generated from protobuf message mcp.protobuf.MCPPrompt
 */
export interface MCPPrompt {
    /**
     * Unique prompt name (e.g. "summarize_todos").
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * Human-readable description of what this prompt does.
     *
     * @generated from protobuf field: string description = 2
     */
    description: string;
    /**
     * Fully-qualified proto message name whose fields define the prompt arguments.
     *
     * @generated from protobuf field: string schema = 3
     */
    schema: string;
}
/**
 * MCPToolOptions configures an individual RPC method as an MCP tool.
 * Used as: option (mcp.protobuf.tool) = { ... };
 *
 * @generated from protobuf message mcp.protobuf.MCPToolOptions
 */
export interface MCPToolOptions {
    /**
     * Override the auto-generated MCP tool name.
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * Override the tool description (defaults to the RPC's leading comment).
     *
     * @generated from protobuf field: string description = 2
     */
    description: string;
    /**
     * When true, this RPC supports MCP progress notifications. Clients may include
     * progressToken in params._meta; the server will send progress updates during
     * execution. Requires a server-streaming RPC whose response has a oneof with
     * mcp.protobuf.MCPProgress and the result type.
     *
     * @generated from protobuf field: optional bool progress = 3
     */
    progress?: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class MCPPrompt$Type extends MessageType<MCPPrompt> {
    constructor() {
        super("mcp.protobuf.MCPPrompt", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "schema", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MCPPrompt>): MCPPrompt {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.description = "";
        message.schema = "";
        if (value !== undefined)
            reflectionMergePartial<MCPPrompt>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MCPPrompt): MCPPrompt {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                case /* string schema */ 3:
                    message.schema = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MCPPrompt, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        /* string schema = 3; */
        if (message.schema !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.schema);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mcp.protobuf.MCPPrompt
 */
export const MCPPrompt = new MCPPrompt$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MCPToolOptions$Type extends MessageType<MCPToolOptions> {
    constructor() {
        super("mcp.protobuf.MCPToolOptions", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "progress", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<MCPToolOptions>): MCPToolOptions {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<MCPToolOptions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MCPToolOptions): MCPToolOptions {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                case /* optional bool progress */ 3:
                    message.progress = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MCPToolOptions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        /* optional bool progress = 3; */
        if (message.progress !== undefined)
            writer.tag(3, WireType.Varint).bool(message.progress);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mcp.protobuf.MCPToolOptions
 */
export const MCPToolOptions = new MCPToolOptions$Type();
