// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "mcp/protobuf/resource.proto" (package "mcp.protobuf", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { MCPMimeType } from "./mime_type";
/**
 * MCPResource describes a data source exposed by an MCP server.
 *
 * @generated from protobuf message mcp.protobuf.MCPResource
 */
export interface MCPResource {
    /**
     * Static URI for a fixed resource (mutually exclusive with pattern).
     *
     * @generated from protobuf field: string uri = 1
     */
    uri: string;
    /**
     * URI template for parameterised resources (e.g. "todo://users/{user}/todos").
     *
     * @generated from protobuf field: string pattern = 2
     */
    pattern: string;
    /**
     * Human-readable display name.
     *
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * Description of what this resource provides.
     *
     * @generated from protobuf field: string description = 4
     */
    description: string;
    /**
     * The MIME type of the resource content.
     *
     * @generated from protobuf field: mcp.protobuf.MCPMimeType mime_type = 5
     */
    mimeType: MCPMimeType;
}
// @generated message type with reflection information, may provide speed optimized methods
class MCPResource$Type extends MessageType<MCPResource> {
    constructor() {
        super("mcp.protobuf.MCPResource", [
            { no: 1, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "pattern", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "mime_type", kind: "enum", T: () => ["mcp.protobuf.MCPMimeType", MCPMimeType] }
        ]);
    }
    create(value?: PartialMessage<MCPResource>): MCPResource {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uri = "";
        message.pattern = "";
        message.name = "";
        message.description = "";
        message.mimeType = 0;
        if (value !== undefined)
            reflectionMergePartial<MCPResource>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MCPResource): MCPResource {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uri */ 1:
                    message.uri = reader.string();
                    break;
                case /* string pattern */ 2:
                    message.pattern = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* string description */ 4:
                    message.description = reader.string();
                    break;
                case /* mcp.protobuf.MCPMimeType mime_type */ 5:
                    message.mimeType = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MCPResource, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uri = 1; */
        if (message.uri !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uri);
        /* string pattern = 2; */
        if (message.pattern !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.pattern);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* string description = 4; */
        if (message.description !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        /* mcp.protobuf.MCPMimeType mime_type = 5; */
        if (message.mimeType !== 0)
            writer.tag(5, WireType.Varint).int32(message.mimeType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mcp.protobuf.MCPResource
 */
export const MCPResource = new MCPResource$Type();
