// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "mcp/protobuf/service_options.proto" (package "mcp.protobuf", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { MCPApp } from "./app";
/**
 * MCPServiceOptions configures MCP behaviour for an entire gRPC service.
 *
 * @generated from protobuf message mcp.protobuf.MCPServiceOptions
 */
export interface MCPServiceOptions {
    /**
     * App-level metadata surfaced to MCP clients.
     *
     * @generated from protobuf field: mcp.protobuf.MCPApp app = 1
     */
    app?: MCPApp;
}
// @generated message type with reflection information, may provide speed optimized methods
class MCPServiceOptions$Type extends MessageType<MCPServiceOptions> {
    constructor() {
        super("mcp.protobuf.MCPServiceOptions", [
            { no: 1, name: "app", kind: "message", T: () => MCPApp }
        ]);
    }
    create(value?: PartialMessage<MCPServiceOptions>): MCPServiceOptions {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<MCPServiceOptions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MCPServiceOptions): MCPServiceOptions {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mcp.protobuf.MCPApp app */ 1:
                    message.app = MCPApp.internalBinaryRead(reader, reader.uint32(), options, message.app);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MCPServiceOptions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mcp.protobuf.MCPApp app = 1; */
        if (message.app)
            MCPApp.internalBinaryWrite(message.app, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mcp.protobuf.MCPServiceOptions
 */
export const MCPServiceOptions = new MCPServiceOptions$Type();
