// Code generated by protoc-gen-mcp. DO NOT EDIT.
// Open Source at Machani Robotics - https://github.com/machanirobotics/protoc-mcp-gen
// source: {{ .SourcePath }}

package {{ .GoPackage }}

import (
	"context"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/encoding/protojson"

	"github.com/machanirobotics/protoc-mcp-gen/pkg/runtime"
)

// JSON schemas for each RPC method, used as the inputSchema for MCP tools.
{{- range $key, $val := .SchemaJSON }}
var {{ $key }}SchemaJSON = {{ backtick }}{{ $val }}{{ backtick }}
{{- end }}

// MCP tool descriptors. Each pairs a schema with a tool name and description
// so that LLM clients can discover and invoke the underlying RPCs.
var (
{{- range $key, $val := .SchemaJSON }}
	{{ $key }}Tool = runtime.MustCreateTool("{{ (index $.ToolMeta $key).Name }}", {{ backtick }}{{ (index $.ToolMeta $key).Description }}{{ backtick }}, {{ $key }}SchemaJSON)
{{- end }}
)

{{- range $svcName, $methods := .Services }}

// {{ $svcName }}MCPServer is the interface that users implement to handle MCP
// tool calls backed by {{ $svcName }} RPCs. Each method mirrors a unary RPC
// from the protobuf service definition.
type {{ $svcName }}MCPServer interface {
{{- range $methName, $tool := $methods }}
	{{ $methName }}(ctx context.Context, req *{{ $tool.RequestType }}) (*{{ $tool.ResponseType }}, error)
{{- end }}
}

// {{ $svcName }}MCPClient is the gRPC client interface used when forwarding MCP
// tool calls to a remote gRPC server. It matches the generated gRPC client stub.
type {{ $svcName }}MCPClient interface {
{{- range $methName, $tool := $methods }}
	{{ $methName }}(ctx context.Context, req *{{ $tool.RequestType }}, opts ...grpc.CallOption) (*{{ $tool.ResponseType }}, error)
{{- end }}
}
{{- end }}

{{- range $svcName, $methods := .Services }}

// Register{{ $svcName }}MCPHandler registers all {{ $svcName }} RPC methods as MCP
// tools on the given server. Each incoming tool call is deserialized from JSON
// into the corresponding protobuf request, dispatched to srv, and the protobuf
// response is serialized back to JSON.
func Register{{ $svcName }}MCPHandler(s *mcp.Server, srv {{ $svcName }}MCPServer, opts ...runtime.Option) {
	cfg := runtime.ApplyOptions(opts...)
{{- range $methName, $tool := $methods }}
	{
		tool := runtime.PrepareToolWithExtras({{ $svcName }}_{{ $methName }}Tool, cfg.ExtraProperties)
		s.AddTool(tool, func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			var pbReq {{ $tool.RequestType }}
			args, ctx := runtime.ExtractExtras(ctx, req.Params.Arguments, cfg)
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(args, &pbReq); err != nil {
				return nil, err
			}
			resp, err := srv.{{ $methName }}(ctx, &pbReq)
			if err != nil {
				return runtime.HandleError(err)
			}
			out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp)
			if err != nil {
				return nil, err
			}
			return runtime.TextResult(string(out)), nil
		})
	}
{{- end }}
}
{{- end }}

{{- range $svcName, $methods := .Services }}

// {{ $svcName }}MCPDefaultBasePath is the default HTTP path prefix for
// {{ $svcName }} MCP endpoints, derived from the protobuf package and service name.
const {{ $svcName }}MCPDefaultBasePath = "{{ index $.ServiceBasePaths $svcName }}"
{{- end }}

{{- range $svcName, $methods := .Services }}

// Serve{{ $svcName }}MCP creates an MCP server, registers the service tools, and
// starts serving using the configured transport (streamable-http, sse, or stdio).
// If cfg.BasePath is empty it defaults to {{ $svcName }}MCPDefaultBasePath.
// This is a blocking call.
func Serve{{ $svcName }}MCP(ctx context.Context, srv {{ $svcName }}MCPServer, cfg *runtime.MCPServerConfig, opts ...runtime.Option) error {
	if cfg.BasePath == "" {
		cfg.BasePath = {{ $svcName }}MCPDefaultBasePath
	}
	return runtime.StartServer(ctx, cfg, func(s *mcp.Server) {
		Register{{ $svcName }}MCPHandler(s, srv, opts...)
	})
}
{{- end }}

{{- range $svcName, $methods := .Services }}

// ForwardTo{{ $svcName }}MCPClient registers all {{ $svcName }} tools on the MCP
// server, but instead of calling a local implementation it forwards every tool
// call to a remote gRPC server via the provided client stub.
func ForwardTo{{ $svcName }}MCPClient(s *mcp.Server, client {{ $svcName }}MCPClient, opts ...runtime.Option) {
	cfg := runtime.ApplyOptions(opts...)
{{- range $methName, $tool := $methods }}
	{
		tool := runtime.PrepareToolWithExtras({{ $svcName }}_{{ $methName }}Tool, cfg.ExtraProperties)
		s.AddTool(tool, func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			var pbReq {{ $tool.RequestType }}
			args, ctx := runtime.ExtractExtras(ctx, req.Params.Arguments, cfg)
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(args, &pbReq); err != nil {
				return nil, err
			}
			resp, err := client.{{ $methName }}(ctx, &pbReq)
			if err != nil {
				return runtime.HandleError(err)
			}
			out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp)
			if err != nil {
				return nil, err
			}
			return runtime.TextResult(string(out)), nil
		})
	}
{{- end }}
}
{{- end }}
