// Code generated by protoc-gen-mcp. DO NOT EDIT.
// Open Source at Machani Robotics - https://github.com/machanirobotics/protoc-mcp-gen
// source: {{ .SourcePath }}

use std::sync::Arc;
use async_trait::async_trait;
use rmcp::{ErrorData as McpError, RoleServer, ServerHandler, ServiceExt, model::*, service::RequestContext};
use serde_json::{self, json, Value};

/// Construct a [`Tool`] descriptor from a tool name, human-readable description,
/// and a raw JSON schema string that defines the expected input parameters.
fn make_tool(name: &str, description: &str, schema_json: &str) -> Tool {
    serde_json::from_value(json!({
        "name": name, "description": description,
        "inputSchema": serde_json::from_str::<Value>(schema_json).unwrap(),
    })).expect("generated tool schema must be valid")
}
{{ range $svcName, $methods := .Services }}
/// JSON schemas for each RPC method, used as the inputSchema for MCP tools.
{{- range $methName, $info := $methods }}
const {{ $info.ConstName }}_SCHEMA_JSON: &str = r##"{{ index $.SchemaJSON (printf "%s_%s" $svcName $methName) }}"##;
{{- end }}

/// Trait that users implement to handle MCP tool calls backed by {{ $svcName }} RPCs.
/// Each method receives a JSON [`Value`] containing the request fields and returns
/// a JSON [`Value`] of the response, or an [`McpError`] on failure.
#[async_trait]
pub trait {{ $svcName }}McpServer: Send + Sync + 'static {
{{- range $methName, $info := $methods }}
    async fn {{ $info.RsMethodName }}(&self, args: Value) -> Result<Value, McpError>;
{{- end }}
}

/// Wrapper that adapts a [`{{ $svcName }}McpServer`] implementation into an
/// [`rmcp::ServerHandler`], making it serveable over any MCP transport
/// (stdio, SSE, or streamable-HTTP).
pub struct {{ $svcName }}McpHandler<T: {{ $svcName }}McpServer> { inner: Arc<T> }

impl<T: {{ $svcName }}McpServer> Clone for {{ $svcName }}McpHandler<T> {
    fn clone(&self) -> Self { Self { inner: Arc::clone(&self.inner) } }
}

impl<T: {{ $svcName }}McpServer> {{ $svcName }}McpHandler<T> {
    /// Wrap the service implementation in an [`Arc`] and return a cloneable handler.
    pub fn new(svc: T) -> Self { Self { inner: Arc::new(svc) } }

    /// Build the list of MCP [`Tool`] descriptors from the embedded JSON schemas.
    fn tools() -> Vec<Tool> {
        vec![
        {{- range $methName, $info := $methods }}
            make_tool("{{ $info.ToolName }}", "{{ $info.Description | rsEscape }}", {{ $info.ConstName }}_SCHEMA_JSON),
        {{- end }}
        ]
    }
}

/// [`ServerHandler`] implementation that bridges MCP `list_tools` and `call_tool`
/// requests to the corresponding methods on the user's [`{{ $svcName }}McpServer`] impl.
impl<T: {{ $svcName }}McpServer> ServerHandler for {{ $svcName }}McpHandler<T> {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation { name: "{{ $svcName }}".into(), version: "0.1.0".into(), ..Default::default() },
            ..Default::default()
        }
    }

    async fn list_tools(&self, _: Option<PaginatedRequestParams>, _: RequestContext<RoleServer>) -> Result<ListToolsResult, McpError> {
        Ok(ListToolsResult { tools: Self::tools(), next_cursor: None, ..Default::default() })
    }

    async fn call_tool(&self, request: CallToolRequestParams, _: RequestContext<RoleServer>) -> Result<CallToolResult, McpError> {
        let args = request.arguments.map_or_else(|| Value::Object(Default::default()), Value::Object);
        match request.name.as_ref() {
        {{- range $methName, $info := $methods }}
            "{{ $info.ToolName }}" => {
                let result = self.inner.{{ $info.RsMethodName }}(args).await?;
                let text = serde_json::to_string(&result)
                    .map_err(|e| McpError::internal_error(format!("serialize response: {e}"), None))?;
                Ok(CallToolResult::success(vec![Content::text(text)]))
            }
        {{- end }}
            _ => Err(McpError::internal_error(format!("unknown tool: {}", request.name), None)),
        }
    }
}

/// Default HTTP base path for {{ $svcName }} MCP endpoints.
pub const {{ $svcName | screamingSnakeCase }}_MCP_DEFAULT_BASE_PATH: &str = "{{ index $.ServiceBasePaths $svcName }}";

/// Transport configuration for [`serve_{{ $svcName | snakeCase }}_mcp`].
pub struct {{ $svcName }}McpTransportConfig {
    /// `"stdio"`, `"sse"`, or `"streamable-http"` (default: `"streamable-http"`).
    pub transport: String,
    /// Bind address for HTTP transports (default: `"0.0.0.0"`).
    pub host: String,
    /// Port for HTTP transports (default: `8080`).
    pub port: u16,
    /// HTTP path prefix (default: [`{{ $svcName | screamingSnakeCase }}_MCP_DEFAULT_BASE_PATH`]).
    pub base_path: String,
}

impl Default for {{ $svcName }}McpTransportConfig {
    fn default() -> Self {
        Self { transport: "streamable-http".into(), host: "0.0.0.0".into(), port: 8080,
               base_path: {{ $svcName | screamingSnakeCase }}_MCP_DEFAULT_BASE_PATH.into() }
    }
}

/// Convenience wrapper that serves {{ $svcName }} MCP over stdio.
/// Blocks until the stdio transport is closed.
pub async fn serve_{{ $svcName | snakeCase }}_mcp_stdio<T: {{ $svcName }}McpServer>(svc: T) -> Result<(), Box<dyn std::error::Error>> {
    let handler = {{ $svcName }}McpHandler::new(svc);
    handler.serve(rmcp::transport::stdio()).await?.waiting().await?;
    Ok(())
}

/// Serve {{ $svcName }} MCP using the transport(s) specified in `config`.
///
/// The `transport` field accepts comma-separated values to run multiple transports
/// concurrently, e.g. `"stdio,streamable-http"`. HTTP-based transports run in a
/// background tokio task while stdio blocks the current task.
pub async fn serve_{{ $svcName | snakeCase }}_mcp<T: {{ $svcName }}McpServer>(
    svc: T, config: {{ $svcName }}McpTransportConfig,
) -> Result<(), Box<dyn std::error::Error>> {
    let handler = {{ $svcName }}McpHandler::new(svc);
    let transports: Vec<&str> = config.transport.split(',').map(|s| s.trim()).filter(|s| !s.is_empty()).collect();
    let has_stdio = transports.iter().any(|t| *t == "stdio");
    let http_transport = transports.iter().find(|t| **t == "sse" || **t == "streamable-http").copied();

    if let Some(_ht) = http_transport {
        use rmcp::transport::streamable_http_server::{
            StreamableHttpServerConfig, StreamableHttpService, session::local::LocalSessionManager,
        };
        let h = handler.clone();
        let http_config = StreamableHttpServerConfig {
            sse_retry: None,
            ..StreamableHttpServerConfig::default()
        };
        let http_service = StreamableHttpService::new(
            move || Ok(h.clone()), Arc::new(LocalSessionManager::default()),
            http_config,
        );
        let app = axum::Router::new().nest_service(&config.base_path, http_service);
        let addr = format!("{}:{}", config.host, config.port);
        let listener = tokio::net::TcpListener::bind(&addr).await?;
        if has_stdio {
            tokio::spawn(async move { axum::serve(listener, app).await.expect("HTTP server failed"); });
        } else {
            axum::serve(listener, app).await?;
            return Ok(());
        }
    }

    if has_stdio {
        handler.serve(rmcp::transport::stdio()).await?.waiting().await?;
    } else if http_transport.is_none() {
        return Err(format!("unsupported transport(s): {}", config.transport).into());
    }
    Ok(())
}
{{- end }}
