// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mcp/protobuf/annotations.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_mcp_protobuf_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*MCPServiceOptions)(nil),
		Field:         51000,
		Name:          "mcp.protobuf.service",
		Tag:           "bytes,51000,opt,name=service",
		Filename:      "mcp/protobuf/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MCPToolOptions)(nil),
		Field:         51001,
		Name:          "mcp.protobuf.tool",
		Tag:           "bytes,51001,opt,name=tool",
		Filename:      "mcp/protobuf/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MCPPrompt)(nil),
		Field:         51002,
		Name:          "mcp.protobuf.prompt",
		Tag:           "bytes,51002,opt,name=prompt",
		Filename:      "mcp/protobuf/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MCPElicitation)(nil),
		Field:         51003,
		Name:          "mcp.protobuf.elicitation",
		Tag:           "bytes,51003,opt,name=elicitation",
		Filename:      "mcp/protobuf/annotations.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional mcp.protobuf.MCPServiceOptions service = 51000;
	E_Service = &file_mcp_protobuf_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional mcp.protobuf.MCPToolOptions tool = 51001;
	E_Tool = &file_mcp_protobuf_annotations_proto_extTypes[1]
	// optional mcp.protobuf.MCPPrompt prompt = 51002;
	E_Prompt = &file_mcp_protobuf_annotations_proto_extTypes[2]
	// optional mcp.protobuf.MCPElicitation elicitation = 51003;
	E_Elicitation = &file_mcp_protobuf_annotations_proto_extTypes[3]
)

var File_mcp_protobuf_annotations_proto protoreflect.FileDescriptor

const file_mcp_protobuf_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1emcp/protobuf/annotations.proto\x12\fmcp.protobuf\x1a google/protobuf/descriptor.proto\x1a\"mcp/protobuf/service_options.proto\x1a\x19mcp/protobuf/prompt.proto\x1a\x1emcp/protobuf/elicitation.proto:_\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xb8\x8e\x03 \x01(\v2\x1f.mcp.protobuf.MCPServiceOptionsR\aservice\x88\x01\x01:U\n" +
	"\x04tool\x12\x1e.google.protobuf.MethodOptions\x18\xb9\x8e\x03 \x01(\v2\x1c.mcp.protobuf.MCPToolOptionsR\x04tool\x88\x01\x01:T\n" +
	"\x06prompt\x12\x1e.google.protobuf.MethodOptions\x18\xba\x8e\x03 \x01(\v2\x17.mcp.protobuf.MCPPromptR\x06prompt\x88\x01\x01:c\n" +
	"\velicitation\x12\x1e.google.protobuf.MethodOptions\x18\xbb\x8e\x03 \x01(\v2\x1c.mcp.protobuf.MCPElicitationR\velicitation\x88\x01\x01Bf\n" +
	"\x10com.mcp.protobufB\x10AnnotationsProtoP\x01Z>github.com/machanirobotics/grpc-mcp-gateway/mcp/protobuf/mcppbb\x06proto3"

var file_mcp_protobuf_annotations_proto_goTypes = []any{
	(*descriptorpb.ServiceOptions)(nil), // 0: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 1: google.protobuf.MethodOptions
	(*MCPServiceOptions)(nil),           // 2: mcp.protobuf.MCPServiceOptions
	(*MCPToolOptions)(nil),              // 3: mcp.protobuf.MCPToolOptions
	(*MCPPrompt)(nil),                   // 4: mcp.protobuf.MCPPrompt
	(*MCPElicitation)(nil),              // 5: mcp.protobuf.MCPElicitation
}
var file_mcp_protobuf_annotations_proto_depIdxs = []int32{
	0, // 0: mcp.protobuf.service:extendee -> google.protobuf.ServiceOptions
	1, // 1: mcp.protobuf.tool:extendee -> google.protobuf.MethodOptions
	1, // 2: mcp.protobuf.prompt:extendee -> google.protobuf.MethodOptions
	1, // 3: mcp.protobuf.elicitation:extendee -> google.protobuf.MethodOptions
	2, // 4: mcp.protobuf.service:type_name -> mcp.protobuf.MCPServiceOptions
	3, // 5: mcp.protobuf.tool:type_name -> mcp.protobuf.MCPToolOptions
	4, // 6: mcp.protobuf.prompt:type_name -> mcp.protobuf.MCPPrompt
	5, // 7: mcp.protobuf.elicitation:type_name -> mcp.protobuf.MCPElicitation
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	4, // [4:8] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_protobuf_annotations_proto_init() }
func file_mcp_protobuf_annotations_proto_init() {
	if File_mcp_protobuf_annotations_proto != nil {
		return
	}
	file_mcp_protobuf_service_options_proto_init()
	file_mcp_protobuf_prompt_proto_init()
	file_mcp_protobuf_elicitation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_protobuf_annotations_proto_rawDesc), len(file_mcp_protobuf_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_mcp_protobuf_annotations_proto_goTypes,
		DependencyIndexes: file_mcp_protobuf_annotations_proto_depIdxs,
		ExtensionInfos:    file_mcp_protobuf_annotations_proto_extTypes,
	}.Build()
	File_mcp_protobuf_annotations_proto = out.File
	file_mcp_protobuf_annotations_proto_goTypes = nil
	file_mcp_protobuf_annotations_proto_depIdxs = nil
}
