// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mcp/protobuf/resource.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPResource describes a data source exposed by an MCP server.
type MCPResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Static URI for a fixed resource (mutually exclusive with pattern).
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// URI template for parameterised resources (e.g. "todo://users/{user}/todos").
	Pattern string `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// Human-readable display name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Description of what this resource provides.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The MIME type of the resource content.
	MimeType MCPMimeType `protobuf:"varint,5,opt,name=mime_type,json=mimeType,proto3,enum=mcp.protobuf.MCPMimeType" json:"mime_type,omitempty"`
	// Resource metadata for security and rendering configuration.
	// For UI resources (uri starting with "ui://"), this contains UI-specific metadata
	// including CSP configuration, permissions, and visual preferences.
	MetaUi        *MCPUIResourceMeta `protobuf:"bytes,6,opt,name=meta_ui,json=metaUi,proto3" json:"meta_ui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPResource) Reset() {
	*x = MCPResource{}
	mi := &file_mcp_protobuf_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPResource) ProtoMessage() {}

func (x *MCPResource) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_protobuf_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPResource.ProtoReflect.Descriptor instead.
func (*MCPResource) Descriptor() ([]byte, []int) {
	return file_mcp_protobuf_resource_proto_rawDescGZIP(), []int{0}
}

func (x *MCPResource) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *MCPResource) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *MCPResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPResource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MCPResource) GetMimeType() MCPMimeType {
	if x != nil {
		return x.MimeType
	}
	return MCPMimeType_MCP_MIME_TYPE_UNSPECIFIED
}

func (x *MCPResource) GetMetaUi() *MCPUIResourceMeta {
	if x != nil {
		return x.MetaUi
	}
	return nil
}

var File_mcp_protobuf_resource_proto protoreflect.FileDescriptor

const file_mcp_protobuf_resource_proto_rawDesc = "" +
	"\n" +
	"\x1bmcp/protobuf/resource.proto\x12\fmcp.protobuf\x1a\x1cmcp/protobuf/mime_type.proto\x1a\x15mcp/protobuf/ui.proto\"\xe1\x01\n" +
	"\vMCPResource\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x126\n" +
	"\tmime_type\x18\x05 \x01(\x0e2\x19.mcp.protobuf.MCPMimeTypeR\bmimeType\x128\n" +
	"\ameta_ui\x18\x06 \x01(\v2\x1f.mcp.protobuf.MCPUIResourceMetaR\x06metaUiBc\n" +
	"\x10com.mcp.protobufB\rResourceProtoP\x01Z>github.com/machanirobotics/grpc-mcp-gateway/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_protobuf_resource_proto_rawDescOnce sync.Once
	file_mcp_protobuf_resource_proto_rawDescData []byte
)

func file_mcp_protobuf_resource_proto_rawDescGZIP() []byte {
	file_mcp_protobuf_resource_proto_rawDescOnce.Do(func() {
		file_mcp_protobuf_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_protobuf_resource_proto_rawDesc), len(file_mcp_protobuf_resource_proto_rawDesc)))
	})
	return file_mcp_protobuf_resource_proto_rawDescData
}

var file_mcp_protobuf_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_protobuf_resource_proto_goTypes = []any{
	(*MCPResource)(nil),       // 0: mcp.protobuf.MCPResource
	(MCPMimeType)(0),          // 1: mcp.protobuf.MCPMimeType
	(*MCPUIResourceMeta)(nil), // 2: mcp.protobuf.MCPUIResourceMeta
}
var file_mcp_protobuf_resource_proto_depIdxs = []int32{
	1, // 0: mcp.protobuf.MCPResource.mime_type:type_name -> mcp.protobuf.MCPMimeType
	2, // 1: mcp.protobuf.MCPResource.meta_ui:type_name -> mcp.protobuf.MCPUIResourceMeta
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mcp_protobuf_resource_proto_init() }
func file_mcp_protobuf_resource_proto_init() {
	if File_mcp_protobuf_resource_proto != nil {
		return
	}
	file_mcp_protobuf_mime_type_proto_init()
	file_mcp_protobuf_ui_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_protobuf_resource_proto_rawDesc), len(file_mcp_protobuf_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_protobuf_resource_proto_goTypes,
		DependencyIndexes: file_mcp_protobuf_resource_proto_depIdxs,
		MessageInfos:      file_mcp_protobuf_resource_proto_msgTypes,
	}.Build()
	File_mcp_protobuf_resource_proto = out.File
	file_mcp_protobuf_resource_proto_goTypes = nil
	file_mcp_protobuf_resource_proto_depIdxs = nil
}
