// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mcp/protobuf/ui.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPUIOptions configures UI metadata for an individual RPC method.
// Used to declare that a tool supports MCP Apps and specify the UI resource.
type MCPUIOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URI of the UI resource to render for this tool.
	// MUST use the `ui://` URI scheme to distinguish UI resources from other MCP resource types.
	// Example: "ui://weather-dashboard"
	ResourceUri   string `protobuf:"bytes,1,opt,name=resource_uri,json=resourceUri,proto3" json:"resource_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPUIOptions) Reset() {
	*x = MCPUIOptions{}
	mi := &file_mcp_protobuf_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPUIOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPUIOptions) ProtoMessage() {}

func (x *MCPUIOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_protobuf_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPUIOptions.ProtoReflect.Descriptor instead.
func (*MCPUIOptions) Descriptor() ([]byte, []int) {
	return file_mcp_protobuf_ui_proto_rawDescGZIP(), []int{0}
}

func (x *MCPUIOptions) GetResourceUri() string {
	if x != nil {
		return x.ResourceUri
	}
	return ""
}

// MCPUIResourceCsp defines Content Security Policy configuration for UI resources.
// Servers declare which external origins their UI needs to access.
// Hosts use this to enforce appropriate CSP headers.
type MCPUIResourceCsp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Origins for network requests (fetch/XHR/WebSocket).
	// Empty or omitted = no external connections (secure default).
	// Maps to CSP `connect-src` directive.
	// Example: ["https://api.weather.com", "wss://realtime.service.com"]
	ConnectDomains []string `protobuf:"bytes,1,rep,name=connect_domains,json=connectDomains,proto3" json:"connect_domains,omitempty"`
	// Origins for static resources (images, scripts, stylesheets, fonts, media).
	// Empty or omitted = no external resources (secure default).
	// Wildcard subdomains supported: "https://*.example.com"
	// Maps to CSP `img-src`, `script-src`, `style-src`, `font-src`, `media-src` directives.
	// Example: ["https://cdn.jsdelivr.net", "https://*.cloudflare.com"]
	ResourceDomains []string `protobuf:"bytes,2,rep,name=resource_domains,json=resourceDomains,proto3" json:"resource_domains,omitempty"`
	// Origins for nested iframes.
	// Empty or omitted = no nested iframes allowed (`frame-src 'none'`).
	// Maps to CSP `frame-src` directive.
	// Example: ["https://www.youtube.com", "https://player.vimeo.com"]
	FrameDomains []string `protobuf:"bytes,3,rep,name=frame_domains,json=frameDomains,proto3" json:"frame_domains,omitempty"`
	// Allowed base URIs for the document.
	// Empty or omitted = only same origin allowed (`base-uri 'self'`).
	// Maps to CSP `base-uri` directive.
	// Example: ["https://cdn.example.com"]
	BaseUriDomains []string `protobuf:"bytes,4,rep,name=base_uri_domains,json=baseUriDomains,proto3" json:"base_uri_domains,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MCPUIResourceCsp) Reset() {
	*x = MCPUIResourceCsp{}
	mi := &file_mcp_protobuf_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPUIResourceCsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPUIResourceCsp) ProtoMessage() {}

func (x *MCPUIResourceCsp) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_protobuf_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPUIResourceCsp.ProtoReflect.Descriptor instead.
func (*MCPUIResourceCsp) Descriptor() ([]byte, []int) {
	return file_mcp_protobuf_ui_proto_rawDescGZIP(), []int{1}
}

func (x *MCPUIResourceCsp) GetConnectDomains() []string {
	if x != nil {
		return x.ConnectDomains
	}
	return nil
}

func (x *MCPUIResourceCsp) GetResourceDomains() []string {
	if x != nil {
		return x.ResourceDomains
	}
	return nil
}

func (x *MCPUIResourceCsp) GetFrameDomains() []string {
	if x != nil {
		return x.FrameDomains
	}
	return nil
}

func (x *MCPUIResourceCsp) GetBaseUriDomains() []string {
	if x != nil {
		return x.BaseUriDomains
	}
	return nil
}

// MCPUIPermissions defines sandbox permissions requested by the UI.
// Servers declare which browser capabilities their UI needs.
// Hosts MAY honor these by setting appropriate iframe `allow` attributes.
// Apps SHOULD NOT assume permissions are granted; use JS feature detection as fallback.
type MCPUIPermissions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request camera access.
	// Maps to Permission Policy `camera` feature.
	Camera bool `protobuf:"varint,1,opt,name=camera,proto3" json:"camera,omitempty"`
	// Request microphone access.
	// Maps to Permission Policy `microphone` feature.
	Microphone bool `protobuf:"varint,2,opt,name=microphone,proto3" json:"microphone,omitempty"`
	// Request geolocation access.
	// Maps to Permission Policy `geolocation` feature.
	Geolocation bool `protobuf:"varint,3,opt,name=geolocation,proto3" json:"geolocation,omitempty"`
	// Request clipboard write access.
	// Maps to Permission Policy `clipboard-write` feature.
	ClipboardWrite bool `protobuf:"varint,4,opt,name=clipboard_write,json=clipboardWrite,proto3" json:"clipboard_write,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MCPUIPermissions) Reset() {
	*x = MCPUIPermissions{}
	mi := &file_mcp_protobuf_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPUIPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPUIPermissions) ProtoMessage() {}

func (x *MCPUIPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_protobuf_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPUIPermissions.ProtoReflect.Descriptor instead.
func (*MCPUIPermissions) Descriptor() ([]byte, []int) {
	return file_mcp_protobuf_ui_proto_rawDescGZIP(), []int{2}
}

func (x *MCPUIPermissions) GetCamera() bool {
	if x != nil {
		return x.Camera
	}
	return false
}

func (x *MCPUIPermissions) GetMicrophone() bool {
	if x != nil {
		return x.Microphone
	}
	return false
}

func (x *MCPUIPermissions) GetGeolocation() bool {
	if x != nil {
		return x.Geolocation
	}
	return false
}

func (x *MCPUIPermissions) GetClipboardWrite() bool {
	if x != nil {
		return x.ClipboardWrite
	}
	return false
}

// MCPUIResourceMeta defines UI resource metadata for security and rendering configuration.
// This metadata may be provided on either the resource listing (resources/list) or on each
// content item (resources/read). When provided on both, the content item value takes precedence.
type MCPUIResourceMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content Security Policy configuration.
	Csp *MCPUIResourceCsp `protobuf:"bytes,1,opt,name=csp,proto3" json:"csp,omitempty"`
	// Sandbox permissions requested by the UI.
	Permissions *MCPUIPermissions `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// Dedicated origin for view.
	// Optional domain for the view's sandbox origin. Useful when views need stable, dedicated
	// origins for OAuth callbacks, CORS policies, or API key allowlists.
	//
	// Host-dependent: The format and validation rules for this field are determined by each host.
	// Servers MUST consult host-specific documentation for the expected domain format.
	// Common patterns include:
	// - Hash-based subdomains (e.g., "{hash}.claudemcpcontent.com")
	// - URL-derived subdomains (e.g., "www-example-com.oaiusercontent.com")
	//
	// If omitted, Host uses default sandbox origin (typically per-conversation).
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	// Visual boundary preference.
	// Boolean controlling whether a visible border and background is provided by the host.
	// Specifying an explicit value is recommended because hosts' defaults may vary.
	// - true: Request visible border + background
	// - false: Request no visible border + background
	// - omitted: host decides border
	PrefersBorder bool `protobuf:"varint,4,opt,name=prefers_border,json=prefersBorder,proto3" json:"prefers_border,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPUIResourceMeta) Reset() {
	*x = MCPUIResourceMeta{}
	mi := &file_mcp_protobuf_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPUIResourceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPUIResourceMeta) ProtoMessage() {}

func (x *MCPUIResourceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_protobuf_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPUIResourceMeta.ProtoReflect.Descriptor instead.
func (*MCPUIResourceMeta) Descriptor() ([]byte, []int) {
	return file_mcp_protobuf_ui_proto_rawDescGZIP(), []int{3}
}

func (x *MCPUIResourceMeta) GetCsp() *MCPUIResourceCsp {
	if x != nil {
		return x.Csp
	}
	return nil
}

func (x *MCPUIResourceMeta) GetPermissions() *MCPUIPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *MCPUIResourceMeta) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *MCPUIResourceMeta) GetPrefersBorder() bool {
	if x != nil {
		return x.PrefersBorder
	}
	return false
}

var File_mcp_protobuf_ui_proto protoreflect.FileDescriptor

const file_mcp_protobuf_ui_proto_rawDesc = "" +
	"\n" +
	"\x15mcp/protobuf/ui.proto\x12\fmcp.protobuf\"1\n" +
	"\fMCPUIOptions\x12!\n" +
	"\fresource_uri\x18\x01 \x01(\tR\vresourceUri\"\xb5\x01\n" +
	"\x10MCPUIResourceCsp\x12'\n" +
	"\x0fconnect_domains\x18\x01 \x03(\tR\x0econnectDomains\x12)\n" +
	"\x10resource_domains\x18\x02 \x03(\tR\x0fresourceDomains\x12#\n" +
	"\rframe_domains\x18\x03 \x03(\tR\fframeDomains\x12(\n" +
	"\x10base_uri_domains\x18\x04 \x03(\tR\x0ebaseUriDomains\"\x95\x01\n" +
	"\x10MCPUIPermissions\x12\x16\n" +
	"\x06camera\x18\x01 \x01(\bR\x06camera\x12\x1e\n" +
	"\n" +
	"microphone\x18\x02 \x01(\bR\n" +
	"microphone\x12 \n" +
	"\vgeolocation\x18\x03 \x01(\bR\vgeolocation\x12'\n" +
	"\x0fclipboard_write\x18\x04 \x01(\bR\x0eclipboardWrite\"\xc6\x01\n" +
	"\x11MCPUIResourceMeta\x120\n" +
	"\x03csp\x18\x01 \x01(\v2\x1e.mcp.protobuf.MCPUIResourceCspR\x03csp\x12@\n" +
	"\vpermissions\x18\x02 \x01(\v2\x1e.mcp.protobuf.MCPUIPermissionsR\vpermissions\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12%\n" +
	"\x0eprefers_border\x18\x04 \x01(\bR\rprefersBorderB]\n" +
	"\x10com.mcp.protobufB\aUIProtoP\x01Z>github.com/machanirobotics/grpc-mcp-gateway/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_protobuf_ui_proto_rawDescOnce sync.Once
	file_mcp_protobuf_ui_proto_rawDescData []byte
)

func file_mcp_protobuf_ui_proto_rawDescGZIP() []byte {
	file_mcp_protobuf_ui_proto_rawDescOnce.Do(func() {
		file_mcp_protobuf_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_protobuf_ui_proto_rawDesc), len(file_mcp_protobuf_ui_proto_rawDesc)))
	})
	return file_mcp_protobuf_ui_proto_rawDescData
}

var file_mcp_protobuf_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mcp_protobuf_ui_proto_goTypes = []any{
	(*MCPUIOptions)(nil),      // 0: mcp.protobuf.MCPUIOptions
	(*MCPUIResourceCsp)(nil),  // 1: mcp.protobuf.MCPUIResourceCsp
	(*MCPUIPermissions)(nil),  // 2: mcp.protobuf.MCPUIPermissions
	(*MCPUIResourceMeta)(nil), // 3: mcp.protobuf.MCPUIResourceMeta
}
var file_mcp_protobuf_ui_proto_depIdxs = []int32{
	1, // 0: mcp.protobuf.MCPUIResourceMeta.csp:type_name -> mcp.protobuf.MCPUIResourceCsp
	2, // 1: mcp.protobuf.MCPUIResourceMeta.permissions:type_name -> mcp.protobuf.MCPUIPermissions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mcp_protobuf_ui_proto_init() }
func file_mcp_protobuf_ui_proto_init() {
	if File_mcp_protobuf_ui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_protobuf_ui_proto_rawDesc), len(file_mcp_protobuf_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_protobuf_ui_proto_goTypes,
		DependencyIndexes: file_mcp_protobuf_ui_proto_depIdxs,
		MessageInfos:      file_mcp_protobuf_ui_proto_msgTypes,
	}.Build()
	File_mcp_protobuf_ui_proto = out.File
	file_mcp_protobuf_ui_proto_goTypes = nil
	file_mcp_protobuf_ui_proto_depIdxs = nil
}
