// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
// 	protoc-gen-mcp {{ .Version }}
// Authors: Machani Robotics - Open Source 2026
// source: {{ .SourcePath }}

package {{ .GoPackage }}

import (
	"context"

{{- range .ExtraImports }}
	{{ . }}
{{- end }}
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/encoding/protojson"

	"github.com/machanirobotics/grpc-mcp-gateway/runtime"
)

// JSON schemas for each RPC method, used as the inputSchema for MCP tools.
{{- range $key, $val := .SchemaJSON }}
var {{ $key }}SchemaJSON = {{ backtick }}{{ $val }}{{ backtick }}
{{- end }}

// MCP tool descriptors. Each pairs a schema with a tool name and description
// so that LLM clients can discover and invoke the underlying RPCs.
var (
{{- range $key, $val := .SchemaJSON }}
	{{ $key }}Tool = runtime.MustCreateTool("{{ (index $.ToolMeta $key).Name }}", {{ backtick }}{{ (index $.ToolMeta $key).Description }}{{ backtick }}, {{ $key }}SchemaJSON)
{{- end }}
)

{{- range $svcName, $methods := .Services }}

// {{ $svcName }}MCPServer is the interface that users implement to handle MCP
// tool calls backed by {{ $svcName }} RPCs. Each method mirrors a unary RPC
// from the protobuf service definition.
type {{ $svcName }}MCPServer interface {
{{- range $methName, $tool := $methods }}
	{{ $methName }}(ctx context.Context, req *{{ $tool.RequestType }}) (*{{ $tool.ResponseType }}, error)
{{- end }}
}

// {{ $svcName }}MCPClient is the gRPC client interface used when forwarding MCP
// tool calls to a remote gRPC server. It matches the generated gRPC client stub.
type {{ $svcName }}MCPClient interface {
{{- range $methName, $tool := $methods }}
	{{ $methName }}(ctx context.Context, req *{{ $tool.RequestType }}, opts ...grpc.CallOption) (*{{ $tool.ResponseType }}, error)
{{- end }}
}
{{- end }}

{{- /* ================================================================== */}}
{{- /* RegisterHandler                                                     */}}
{{- /* ================================================================== */}}

{{- range $svcName, $methods := .Services }}
{{- $svcOpts := index $.ServiceOpts $svcName }}

// Register{{ $svcName }}MCPHandler registers all {{ $svcName }} RPC methods as MCP
// tools, prompts, resources, and apps on the given server based on proto options.
func Register{{ $svcName }}MCPHandler(s *mcp.Server, srv {{ $svcName }}MCPServer, opts ...runtime.Option) {
	cfg := runtime.ApplyOptions(opts...)
{{- if and $svcOpts $svcOpts.App }}
	appResourceURI := runtime.AppResourceURI("{{ $svcName }}")
{{- end }}

{{- range $methName, $tool := $methods }}
	{
		tool := runtime.PrepareToolWithExtras({{ $svcName }}_{{ $methName }}Tool, cfg.ExtraProperties)
{{- if and $svcOpts $svcOpts.App }}
		tool = runtime.SetToolAppMeta(tool, appResourceURI)
{{- end }}
		s.AddTool(tool, func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			elicitResult, elicitErr := runtime.RunElicitation(ctx, req.Session, "{{ $tool.MethodOpts.Elicitation.Message }}", []runtime.ElicitField{
			{{- range $tool.MethodOpts.Elicitation.Fields }}
				{Name: "{{ .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}, Type: "{{ .Type }}"{{- if .EnumValues }}, EnumValues: []string{ {{- range .EnumValues }}"{{ . }}", {{ end }}}{{- end }}},
			{{- end }}
			})
			if elicitErr != nil {
				return nil, elicitErr
			}
			if elicitResult.Action != "accept" {
				return runtime.TextResult("Action cancelled by user."), nil
			}
{{- end }}
			var pbReq {{ $tool.RequestType }}
			args, ctx := runtime.ExtractExtras(ctx, req.Params.Arguments, cfg)
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(args, &pbReq); err != nil {
				return nil, err
			}
			resp, err := srv.{{ $methName }}(ctx, &pbReq)
			if err != nil {
				return runtime.HandleError(err)
			}
			out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp)
			if err != nil {
				return nil, err
			}
			return runtime.TextResult(string(out)), nil
		})
	}
{{- end }}
{{- if and $svcOpts $svcOpts.Resources }}

{{- range $svcOpts.Resources }}
{{- if .URI }}
	s.AddResource(&mcp.Resource{
		URI:         "{{ .URI }}",
		Name:        "{{ .Name }}",
		Description: "{{ .Description }}",
		MIMEType:    "{{ .MimeType }}",
	}, runtime.DefaultResourceHandler())
{{- end }}
{{- if .URITemplate }}
	s.AddResourceTemplate(&mcp.ResourceTemplate{
		URITemplate: "{{ .URITemplate }}",
		Name:        "{{ .Name }}",
		Description: "{{ .Description }}",
		MIMEType:    "{{ .MimeType }}",
	}, runtime.DefaultResourceHandler())
{{- end }}
{{- end }}
{{- end }}
{{- $hasMethodPrompts := false }}
{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}{{ $hasMethodPrompts = true }}{{ end }}
{{- end }}
{{- if $hasMethodPrompts }}

{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}
	s.AddPrompt(&mcp.Prompt{
		Name:        "{{ $tool.MethodOpts.Prompt.Name }}",
		Description: "{{ $tool.MethodOpts.Prompt.Description }}",
		Arguments: []*mcp.PromptArgument{
		{{- range $tool.MethodOpts.Prompt.Arguments }}
			{Name: "{{ .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}},
		{{- end }}
		},
	}, runtime.DefaultPromptHandler("{{ escapeQuotes $tool.MethodOpts.Prompt.Description }}"))
{{- end }}
{{- end }}
{{- end }}
{{- if and $svcOpts $svcOpts.App }}

	s.AddResource(&mcp.Resource{
		URI:      appResourceURI,
		Name:     "{{ escapeQuotes $svcOpts.App.Name }}",
		MIMEType: "text/html",
	}, runtime.DefaultAppResourceHandler("{{ escapeQuotes $svcOpts.App.Name }}", "{{ $svcOpts.App.Version }}", "{{ escapeQuotes $svcOpts.App.Description }}"))
{{- end }}
}
{{- end }}

{{- range $svcName, $methods := .Services }}

// {{ $svcName }}MCPDefaultBasePath is the default HTTP path prefix for
// {{ $svcName }} MCP endpoints, derived from the protobuf package and service name.
const {{ $svcName }}MCPDefaultBasePath = "{{ index $.ServiceBasePaths $svcName }}"
{{- end }}

{{- range $svcName, $methods := .Services }}
{{- $svcOpts := index $.ServiceOpts $svcName }}

// {{ $svcName }}CompletionMap returns a map of "promptName:argName" → allowed
// values, built from enum_values declared in the proto MCP options.
func {{ $svcName }}CompletionMap() map[string][]string {
	m := map[string][]string{}
{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}
{{- $pName := $tool.MethodOpts.Prompt.Name }}
{{- range $tool.MethodOpts.Prompt.Arguments }}
{{- if .EnumValues }}
	m["{{ $pName }}:{{ .Name }}"] = []string{ {{- range .EnumValues }}"{{ . }}", {{ end }}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
	return m
}

// Serve{{ $svcName }}MCP creates an MCP server, registers the service tools, and
// starts serving using the configured transport (streamable-http, sse, or stdio).
// Uses the proto-derived BasePath. This is a blocking call.
func Serve{{ $svcName }}MCP(ctx context.Context, srv {{ $svcName }}MCPServer, cfg *runtime.MCPServerConfig, opts ...runtime.Option) error {
	// Set the proto-derived path as the generated default
	cfg.GeneratedBasePath = {{ $svcName }}MCPDefaultBasePath

	// Wire completion handler for prompt arguments with enum_values.
	completionMap := {{ $svcName }}CompletionMap()
	if len(completionMap) > 0 {
		if cfg.ServerOptions == nil {
			cfg.ServerOptions = &mcp.ServerOptions{}
		}
		cfg.ServerOptions.CompletionHandler = runtime.CompletionHandlerFromEnums(completionMap)
	}

	return runtime.StartServer(ctx, cfg, func(s *mcp.Server) {
		Register{{ $svcName }}MCPHandler(s, srv, opts...)
	})
}
{{- end }}

{{- range $svcName, $methods := .Services }}
{{- $svcOpts := index $.ServiceOpts $svcName }}

// ForwardTo{{ $svcName }}MCPClient registers all {{ $svcName }} tools, prompts,
// resources, and apps on the MCP server, forwarding every tool call to a
// remote gRPC server via the provided client stub.
func ForwardTo{{ $svcName }}MCPClient(s *mcp.Server, client {{ $svcName }}MCPClient, opts ...runtime.Option) {
	cfg := runtime.ApplyOptions(opts...)
{{- if and $svcOpts $svcOpts.App }}
	appResourceURI := runtime.AppResourceURI("{{ $svcName }}")
{{- end }}

{{- range $methName, $tool := $methods }}
	{
		tool := runtime.PrepareToolWithExtras({{ $svcName }}_{{ $methName }}Tool, cfg.ExtraProperties)
{{- if and $svcOpts $svcOpts.App }}
		tool = runtime.SetToolAppMeta(tool, appResourceURI)
{{- end }}
		s.AddTool(tool, func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			elicitResult, elicitErr := runtime.RunElicitation(ctx, req.Session, "{{ $tool.MethodOpts.Elicitation.Message }}", []runtime.ElicitField{
			{{- range $tool.MethodOpts.Elicitation.Fields }}
				{Name: "{{ .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}, Type: "{{ .Type }}"{{- if .EnumValues }}, EnumValues: []string{ {{- range .EnumValues }}"{{ . }}", {{ end }}}{{- end }}},
			{{- end }}
			})
			if elicitErr != nil {
				return nil, elicitErr
			}
			if elicitResult.Action != "accept" {
				return runtime.TextResult("Action cancelled by user."), nil
			}
{{- end }}
			var pbReq {{ $tool.RequestType }}
			args, ctx := runtime.ExtractExtras(ctx, req.Params.Arguments, cfg)
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(args, &pbReq); err != nil {
				return nil, err
			}
			ctx = runtime.ForwardMetadata(ctx)
			resp, err := client.{{ $methName }}(ctx, &pbReq)
			if err != nil {
				return runtime.HandleError(err)
			}
			out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp)
			if err != nil {
				return nil, err
			}
			return runtime.TextResult(string(out)), nil
		})
	}
{{- end }}
{{- if and $svcOpts $svcOpts.Resources }}

{{- range $svcOpts.Resources }}
{{- if .URI }}
	s.AddResource(&mcp.Resource{
		URI:         "{{ .URI }}",
		Name:        "{{ .Name }}",
		Description: "{{ .Description }}",
		MIMEType:    "{{ .MimeType }}",
	}, runtime.DefaultResourceHandler())
{{- end }}
{{- if .URITemplate }}
	s.AddResourceTemplate(&mcp.ResourceTemplate{
		URITemplate: "{{ .URITemplate }}",
		Name:        "{{ .Name }}",
		Description: "{{ .Description }}",
		MIMEType:    "{{ .MimeType }}",
	}, runtime.DefaultResourceHandler())
{{- end }}
{{- end }}
{{- end }}
{{- $hasMethodPrompts := false }}
{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}{{ $hasMethodPrompts = true }}{{ end }}
{{- end }}
{{- if $hasMethodPrompts }}

{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}
	s.AddPrompt(&mcp.Prompt{
		Name:        "{{ $tool.MethodOpts.Prompt.Name }}",
		Description: "{{ $tool.MethodOpts.Prompt.Description }}",
		Arguments: []*mcp.PromptArgument{
		{{- range $tool.MethodOpts.Prompt.Arguments }}
			{Name: "{{ .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}},
		{{- end }}
		},
	}, runtime.DefaultPromptHandler("{{ escapeQuotes $tool.MethodOpts.Prompt.Description }}"))
{{- end }}
{{- end }}
{{- end }}
{{- if and $svcOpts $svcOpts.App }}

	s.AddResource(&mcp.Resource{
		URI:      appResourceURI,
		Name:     "{{ escapeQuotes $svcOpts.App.Name }}",
		MIMEType: "text/html",
	}, runtime.DefaultAppResourceHandler("{{ escapeQuotes $svcOpts.App.Name }}", "{{ $svcOpts.App.Version }}", "{{ escapeQuotes $svcOpts.App.Description }}"))
{{- end }}
}
{{- end }}
